export { default as Administrador } from './administradores/Administradores'
export { default as AgregarPeliculas } from './agregarPeliculas/agregarPeliculas'
export { default as PeliculasSearch} from './search/PeliculasSearch'
export { default as SeriesSearch} from './search/SeriesSearch'
export { default as Perfil } from './perfil/Perfil'
export { default as Turnos } from './turnos/Turnos'
export { default as Inicio } from './inicio/Inicio'